name: Validate Proto Files

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install buf CLI
        uses: bufbuild/buf-setup-action@v1

      - name: Lint proto files
        uses: bufbuild/buf-lint-action@v1
        with:
          input: protos

      # Run breaking change detection for Protobuf sources against the current `main` branch
#      - name: Check proto files for breaking changes
#        uses: bufbuild/buf-breaking-action@v1
#        with:
#          against: https://github.com/ladral/cunfin.git#branch=main,subdir=protos